

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class mainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainFrame.class.getName());

    /**
     * Creates new form mainFrame
     */
    
    
    public mainFrame() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        playbutton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gameName.setBackground(new java.awt.Color(0, 51, 51));
        gameName.setFont(new java.awt.Font("Pix32", 1, 60)); // NOI18N
        gameName.setForeground(new java.awt.Color(0, 51, 51));
        gameName.setText("WORDSTORM");
        getContentPane().add(gameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 310, 70));

        jLabel1.setFont(new java.awt.Font("Pix32", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Type the falling words before they hit the ground!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        playbutton.setBackground(new java.awt.Color(204, 204, 255));
        playbutton.setFont(new java.awt.Font("Pix32", 3, 19)); // NOI18N
        playbutton.setText("PLAY");
        playbutton.addActionListener(this::playbuttonActionPerformed);
        getContentPane().add(playbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 191, 62));

        settingsButton.setBackground(new java.awt.Color(204, 204, 255));
        settingsButton.setFont(new java.awt.Font("Pix32", 3, 18)); // NOI18N
        settingsButton.setText("HOW TO PLAY");
        settingsButton.addActionListener(this::settingsButtonActionPerformed);
        getContentPane().add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 191, 59));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sky.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playbuttonActionPerformed
        // TODO add your handling code here:
        gameModeFrame gmf = new gameModeFrame();
        gmf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_playbuttonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
        tutorialFrame sf = new tutorialFrame();
        sf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton playbutton;
    private javax.swing.JButton settingsButton;
    // End of variables declaration//GEN-END:variables
}
